apiVersion: v1
kind: Service
metadata:
  name: nginx-deployment
spec:
  # Loadbalancer を指定して、外部アクセスを可能に
  type: LoadBalancer
  # ラベルが nginx となっているPodに分散させる
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
